### ISSUE TITLE
Crash on TradeOfferChange

### ISSUE THREAD

**Issue by joekiller** [idinium96/tf2autobot#118]
I am running 6f5a769da86a06641c59549ce56d96da06861eff

```
0|tf2autobot-1  | 2020-11-12 13:34:30 info: Message sent to <name> <id>/pre ❌ Ohh nooooes! The offer is no longer available. Reason: The offer has been active for a while. If the offer was just created, this is likely an issue on Steam's end. Please try again..
0|tf2autobot-1  | 2020-11-12 13:34:31 info: Message sent to <name> (<id>): /pre ✅ Success! The offer went through successfully.
0|tf2autobot-1  | 2020-11-12 13:34:31 trade: Offer # with <id> has been accepted.
0|tf2autobot-1  | 2020-11-12 13:34:31 error: TF2Autobot crashed! Please create an issue with the following log:
0|tf2autobot-1  | package.version: 1.6.7; node: v12.19.0 win32 x64}
0|tf2autobot-1  | Stack trace:
0|tf2autobot-1  | TypeError: Cannot read property 'length' of undefined
0|tf2autobot-1  |     at MyHandler.onTradeOfferChanged (C:\tf2autobot\dist\classes\MyHandler.js:1441:41)
0|tf2autobot-1  |     at C:\tf2autobot\dist\classes\Trades.js:547:30
0|tf2autobot-1  |     at tryCatcher (C:\tf2autobot\node_modules\bluebird\js\release\util.js:16:23)
0|tf2autobot-1  |     at Promise.successAdapter [as _fulfillmentHandler0] (C:\tf2autobot\node_modules\bluebird\js\release\nodeify.js:22:30)
0|tf2autobot-1  |     at Promise._settlePromise (C:\tf2autobot\node_modules\bluebird\js\release\promise.js:601:21)
0|tf2autobot-1  |     at Promise._settlePromise0 (C:\tf2autobot\node_modules\bluebird\js\release\promise.js:649:10)
0|tf2autobot-1  |     at Promise._settlePromises (C:\tf2autobot\node_modules\bluebird\js\release\promise.js:729:18)
0|tf2autobot-1  |     at _drainQueueStep (C:\tf2autobot\node_modules\bluebird\js\release\async.js:93:12)
0|tf2autobot-1  |     at _drainQueue (C:\tf2autobot\node_modules\bluebird\js\release\async.js:86:9)
0|tf2autobot-1  |     at Async._drainQueues (C:\tf2autobot\node_modules\bluebird\js\release\async.js:102:5)
0|tf2autobot-1  |     at Immediate.Async.drainQueues (C:\tf2autobot\node_modules\bluebird\js\release\async.js:15:14)
0|tf2autobot-1  |     at processImmediate (internal/timers.js:461:21)
```

**Comment by idinium96** [comment]
Thanks for the report. Releasing v1.7.0.1.
