### ISSUE TITLE
Missing conversion rate for keys in refined

### ISSUE THREAD

**Issue by joekiller** [idinium96/tf2autobot#133]
Not totally sure what was provoking this but I am on commit 6c558ddc05b8bfa166427840e85ecde11138948a

~~This can be worked around by setting ENABLE_AUTOKEYS to false.~~ this doesn't work

```
Checking listings for 983 items...
Done checking all
info: TF2Autobot v1.7.0 is ready! 983 items in pricelist, 0 listings on www.backpack.tf (cap: 1332)
Error: Missing conversion rate for keys in refined
    at Currencies.toValue (C:\tf2autobot\node_modules\tf2-currencies\lib\currencies.js:40:15)
    at Autokeys.check (C:\tf2autobot\dist\classes\Autokeys.js:101:88)
    at MyHandler.onReady (C:\tf2autobot\dist\classes\MyHandler.js:267:23)
    at C:\tf2autobot\dist\classes\Bot.js:335:30
    at wrapper (C:\tf2autobot\node_modules\async\dist\async.js:268:20)
    at replenish (C:\tf2autobot\node_modules\async\dist\async.js:435:29)
    at iterateeCallback (C:\tf2autobot\node_modules\async\dist\async.js:424:21)
    at C:\tf2autobot\node_modules\async\dist\async.js:321:20
    at tryCatcher (C:\tf2autobot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\tf2autobot\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\tf2autobot\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\tf2autobot\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\tf2autobot\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\tf2autobot\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\tf2autobot\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\tf2autobot\node_modules\bluebird\js\release\async.js:102:5)
```

[error.log](https://github.com/idinium96/tf2autobot/files/5542731/error.log)

**To Reproduce**

1. Just let it run?

Version: 
6c558ddc05b8bfa166427840e85ecde11138948a

**Comment by joekiller** [comment]
trying to catch it in debug...

**Comment by joekiller** [comment]
Attached is an image of what the debugger sees. 

![image](https://user-images.githubusercontent.com/1022919/99190989-d3800880-2737-11eb-8c8a-102231c9d6aa.png)

**Comment by joekiller** [comment]
This issue is gone now but the problem seems to be that the key price in metal had keys in it. doh!

bad response:
`0|tf2autobot-1  | 2020-11-15 12:09:49 debug: Key rate is set based current key prices. {"buy":{"keys":1,"metal":4.22},"sell":{"keys":1,"metal":4.55},"src":"sbn","time":1605456641}`

good response:
`0|tf2autobot-1  | 2020-11-15 13:59:59 debug: Key rate is set based current key prices. {"buy":{"keys":0,"metal":54.44},"sell":{"keys":0,"metal":54.55},"src":"sbn","time":1605466512}`

**Comment by joekiller** [comment]
aethez suggesting not using sbn for key prices doh. It may be that more validation of what a "valid" response could help. then it could switch between bp, sbn or, perhaps what it was manually

![image](https://user-images.githubusercontent.com/1022919/99194323-b6096980-274c-11eb-967b-d5e9dd4a1d8a.png)

**Comment by joekiller** [comment]
Record of bad entry:
https://discord.com/channels/696021490411241483/739458780319973398/777566281389834242
![image](https://user-images.githubusercontent.com/1022919/99194522-d1c13f80-274d-11eb-8c09-08959e1d20f5.png)

Record of good entry that brough things back online:
![image](https://user-images.githubusercontent.com/1022919/99194553-f5848580-274d-11eb-8846-b547980893d8.png)

**Comment by idinium96** [comment]
right. I should not use sbn.tf for key prices.
