### ISSUE TITLE
EYldRefreshAppIfNecessary failed with EResult 55

### ISSUE THREAD

**Issue by joekiller** [idinium96/tf2autobot#216]
I'm unsure what happened but the crash occurred at startup. A restart fixed it however my bot didn't recover from the crash automatically with pm2. this v2.2.0

```
Error: EYldRefreshAppIfNecessary failed with EResult 55
    at C:\trading\tf2autobot\node_modules\steamcommunity\components\users.js:447:12
    at SteamCommunity._checkHttpError (C:\trading\tf2autobot\node_modules\steamcommunity\components\http.js:110:3)
    at Request._callback (C:\trading\tf2autobot\node_modules\steamcommunity\components\http.js:50:61)
    at Request.self.callback (C:\trading\tf2autobot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (C:\trading\tf2autobot\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:314:20)
    at Gunzip.<anonymous> (C:\trading\tf2autobot\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at Gunzip.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by idinium96** [comment]
Please ask Steam for the fix. Thanks.
