### ISSUE TITLE
Crash with bad steamID message input

### ISSUE THREAD

**Issue by joekiller** [idinium96/tf2autobot#97]
I did a `!message <steamname> "blah"` instead of `!message <steamid> "blah"` and it threw the following error:

```
0|tf2autobot  | 2020-10-29 16:11:08 error: TF2Autobot crashed! Please create an issue with the following log:
0|tf2autobot  | package.version: 1.5.5; node: v12.19.0 win32 x64}
0|tf2autobot  | Stack trace:
0|tf2autobot  | Error: Unknown SteamID input format "joekiller"
0|tf2autobot  |     at new SteamID (C:\tf2autobot\node_modules\steamid\index.js:101:9)
0|tf2autobot  |     at Commands.messageCommand (C:\tf2autobot\dist\classes\Commands.js:606:38)
0|tf2autobot  |     at Commands.processMessage (C:\tf2autobot\dist\classes\Commands.js:186:18)
0|tf2autobot  |     at MyHandler.onMessage (C:\tf2autobot\dist\classes\MyHandler.js:335:23)
0|tf2autobot  |     at Bot.onMessage (C:\tf2autobot\dist\classes\Bot.js:527:22)
0|tf2autobot  |     at Immediate.<anonymous> (C:\tf2autobot\dist\classes\Bot.js:142:21)
0|tf2autobot  |     at processImmediate (internal/timers.js:461:21)
```

Version: 
this is off the dev branch: 82435460f2cfb56b1b7d044d6b453a5c9928a2df

**Comment by idinium96** [comment]
Thanks for the report 👍
